name: demo-11
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2024.3.11=hecd8cb5_0
  - libffi=3.4.4=hecd8cb5_1
  - ncurses=6.4=hcec6c5f_0
  - openssl=3.0.14=h46256e1_0
  - pip=24.0=py311hecd8cb5_0
  - python=3.11.9=hf27a42d_0
  - readline=8.2=hca72f7f_0
  - setuptools=69.5.1=py311hecd8cb5_0
  - sqlite=3.45.3=h6c40b1e_0
  - tk=8.6.14=h4d00af3_0
  - wheel=0.43.0=py311hecd8cb5_0
  - xz=5.4.6=h6c40b1e_1
  - zlib=1.2.13=h4b97444_1
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - anyio==4.4.0
      - asgiref==3.8.1
      - asteval==1.0.0
      - attrs==23.2.0
      - backoff==2.2.1
      - bcrypt==4.1.3
      - blinker==1.8.2
      - build==1.2.1
      - cachetools==5.3.3
      - cerberus==1.3.5
      - certifi==2024.6.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - chroma-hnswlib==0.7.3
      - chromadb==0.5.3
      - circuitbreaker==1.4.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - coloredlogs==15.0.1
      - contourpy==1.2.1
      - cryptography==42.0.8
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - deprecated==1.2.14
      - dnspython==2.6.1
      - email-validator==2.2.0
      - faiss-cpu==1.8.0.post1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - filelock==3.15.4
      - flatbuffers==24.3.25
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.31.0
      - googleapis-common-protos==1.63.2
      - greenlet==3.0.3
      - grpcio==1.64.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.4
      - humanfriendly==10.0
      - idna==3.7
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - inflection==0.5.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - kubernetes==30.1.0
      - langchain==0.2.6
      - langchain-chroma==0.1.2
      - langchain-community==0.2.6
      - langchain-core==0.2.11
      - langchain-text-splitters==0.2.2
      - langsmith==0.1.83
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.21.3
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - mmh3==4.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - numpy==1.26.4
      - oauthlib==3.2.2
      - oci==2.129.1
      - ocifs==1.3.1
      - onnxruntime==1.16.3
      - opentelemetry-api==1.25.0
      - opentelemetry-exporter-otlp-proto-common==1.25.0
      - opentelemetry-exporter-otlp-proto-grpc==1.25.0
      - opentelemetry-instrumentation==0.46b0
      - opentelemetry-instrumentation-asgi==0.46b0
      - opentelemetry-instrumentation-fastapi==0.46b0
      - opentelemetry-proto==1.25.0
      - opentelemetry-sdk==1.25.0
      - opentelemetry-semantic-conventions==0.46b0
      - opentelemetry-util-http==0.46b0
      - oracle-ads==2.11.14
      - orjson==3.10.6
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.4.0
      - posthog==3.5.0
      - protobuf==4.25.3
      - psutil==6.0.0
      - pyarrow==16.1.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pydantic==2.8.0
      - pydantic-core==2.20.0
      - pydeck==0.9.1
      - pygments==2.18.0
      - pyopenssl==24.1.0
      - pyparsing==3.1.2
      - pypdf==4.2.0
      - pypika==0.48.9
      - pyproject-hooks==1.1.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-jsonschema-objects==0.5.5
      - python-multipart==0.0.9
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - scikit-learn==1.5.0
      - scipy==1.14.0
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlalchemy==2.0.31
      - starlette==0.37.2
      - streamlit==1.36.0
      - sympy==1.12.1
      - tabulate==0.9.0
      - tenacity==8.4.2
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - toolz==0.12.1
      - tornado==6.4.1
      - tqdm==4.66.4
      - typer==0.12.3
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - ujson==5.10.0
      - urllib3==2.2.2
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - watchfiles==0.22.0
      - websocket-client==1.8.0
      - websockets==12.0
      - wrapt==1.16.0
      - yarl==1.9.4
      - zipp==3.19.2
prefix: /opt/anaconda3/envs/demo-11
